### ISSUE TITLE
Xbox App Pause Issues/ Hamburger menu does not work

### ISSUE THREAD

**Issue by b4seball3rd** [jellyfin/jellyfin-uwp#21] opened 2020-06-10 14:45 UTC
**Describe the bug**

When starting a movie or show, pressing the A button on the controller does not pause the video .You have to move the left joy stick to pull the menu and even then the pause does not work. You can fast forward/rewind but no pause. 

-When selecting the hamburger menu from the top left in the Xbox application. The screen gets dark as if a menu comes up but nothing happens

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]   Xbox/ Windows
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.] Xbox
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Xbox
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] Jellyfin_0.8.0.70x64
 -Playback: Direct Play/Transcode
-Plugins: Anime, Fanart
-Base URL: None
-Networking: Host
-Storage: Local and NFS / Network

**To Reproduce**

1. Go to Jelly Fin.'
2. Click on 'Jelly fin to launch
3. Scroll down to a movie and start it 
4. After movie starts try pausing it

Menu Issue
1. Open App
2. Login
3. Highlight hamburger menu in top left

**Expected behavior**

2nd Issue: Hamburger menu expands and shows options 

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by anthonylavado** [comment] 2020-06-11 17:28
Duplicate of #9 and #10.

**Closed by anthonylavado** 2020-06-11 17:28 UTC
Labels: duplicate
