### ISSUE TITLE
Won't appear on Windows Store for PC (only xbox)

### ISSUE THREAD

**Issue by spiriapbergeron** [jellyfin/jellyfin-uwp#23] opened 2020-07-10 08:28 UTC
On the windows store, it only appears to be available for XBOX, not PC.
 
I tried to unzip the .appxupload, to find the .appxbundle, and install from that, but Win10 won't let me install it because the certificate isn't valid, and the certificate is nowehere to be found.

so it appears it's impossible to install at this time unless you're a developer and you can build the damn thing.

**Comment by MrTimscampi** [comment] 2020-07-10 08:49
Closing as a duplicate of #22.

**Closed by MrTimscampi** 2020-07-10 08:50 UTC
Labels: duplicate
